import * as fs from 'fs';
import * as mammoth from 'mammoth';
import type { Extractor, ExtractionResult, ExtractedContent } from './types';
import { truncateToWordLimit, withTimeout } from './extractor-utils';

/**
 * DOCX Extractor - extracts text from Microsoft Word documents
 * Supports: .docx
 */
export class DocxExtractor implements Extractor {
  readonly id = 'docx-extractor';
  readonly version = '1.0.0';
  
  readonly supportedExtensions = ['docx'];

  canExtract(extension: string): boolean {
    return this.supportedExtensions.includes(extension.toLowerCase());
  }

  async extract(filePath: string, extension: string): Promise<ExtractionResult> {
    try {
      // Check file size (skip files larger than 50MB)
      const stats = fs.statSync(filePath);
      const maxSize = 50 * 1024 * 1024; // 50MB
      if (stats.size > maxSize) {
        return {
          success: false,
          content: null,
          error: `DOCX too large (${Math.round(stats.size / 1024 / 1024)}MB), skipping`,
          extractorVersion: this.version,
        };
      }

      const dataBuffer = await withTimeout(
        fs.promises.readFile(filePath),
        60000, // 60 second timeout
        10000, // 10 second warning
        filePath
      );
      
      const result = await withTimeout(
        mammoth.extractRawText({ buffer: dataBuffer }),
        60000, // 60 second timeout
        10000, // 10 second warning
        filePath
      );
      
      const rawText = result.value || '';
      
      // Truncate to 1000 words max for scalability
      const extractedText = truncateToWordLimit(rawText);
      
      // Extract keywords from text
      const keywords = this.extractKeywords(extractedText);
      
      const extractedContent: ExtractedContent = {
        contentType: 'document',
        extractedText,
        summary: null, // Summary will be generated by Summary Agent
        keywords,
        metadata: {
          size: stats.size,
          extension,
          wordCount: extractedText.split(/\s+/).filter(w => w.length > 0).length,
          lineCount: extractedText.split('\n').length,
          originalWordCount: rawText.split(/\s+/).filter(w => w.length > 0).length,
          truncated: rawText.length !== extractedText.length,
        },
      };

      return {
        success: true,
        content: extractedContent,
        extractorVersion: this.version,
      };
    } catch (error) {
      return {
        success: false,
        content: null,
        error: error instanceof Error ? error.message : 'Unknown error',
        extractorVersion: this.version,
      };
    }
  }

  private extractKeywords(text: string): string[] {
    const keywords: string[] = ['docx', 'word'];
    
    // Simple keyword extraction
    const commonWords = ['report', 'document', 'proposal', 'letter', 'memo',
                         'contract', 'agreement', 'resume', 'cv', 'thesis',
                         'dissertation', 'paper', 'article'];
    
    const lowerText = text.toLowerCase();
    for (const word of commonWords) {
      if (lowerText.includes(word)) {
        keywords.push(word);
      }
    }
    
    return [...new Set(keywords)];
  }
}
