import * as fs from 'fs';
import type { Extractor, ExtractionResult, ExtractedContent } from './types';

/**
 * Image Extractor - reads image files for processing by Summary Agent
 * Supports: .jpg, .jpeg, .png, .gif, .webp, .svg, .bmp, .tiff, .heic
 * 
 * Note: GPT-5-nano can handle images directly, so we don't need Vision API here.
 * The Summary Agent will process the image directly.
 */
export class ImageExtractor implements Extractor {
  readonly id = 'image-extractor';
  readonly version = '1.0.0';
  
  readonly supportedExtensions = [
    'jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'ico', 'bmp', 'tiff', 'tif', 'heic', 'heif',
  ];

  canExtract(extension: string): boolean {
    return this.supportedExtensions.includes(extension.toLowerCase());
  }

  async extract(filePath: string, extension: string): Promise<ExtractionResult> {
    try {
      // Check file size (OpenAI has 20MB limit)
      const stats = fs.statSync(filePath);
      const maxSize = 20 * 1024 * 1024; // 20MB
      if (stats.size > maxSize) {
        return {
          success: false,
          content: null,
          error: `Image too large (${Math.round(stats.size / 1024 / 1024)}MB), skipping`,
          extractorVersion: this.version,
        };
      }

      // Read image buffer - Summary Agent will process it directly with GPT-5-nano
      const imageBuffer = await fs.promises.readFile(filePath);
      const mimeType = this.getMimeType(extension);
      
      // Extractors only extract raw content - classification is done by Summary Agent
      // For images, we store the buffer in metadata so Summary Agent can use it directly
      const extractedContent: ExtractedContent = {
        contentType: 'image',
        extractedText: null, // No text extraction needed - Summary Agent handles image directly
        summary: null, // Summary will be generated by Summary Agent
        keywords: ['image', extension.toLowerCase()],
        metadata: {
          size: stats.size,
          extension,
          mimeType,
          // Store buffer as base64 for Summary Agent
          imageBuffer: imageBuffer.toString('base64'),
        },
      };

      return {
        success: true,
        content: extractedContent,
        extractorVersion: this.version,
      };
    } catch (error) {
      return {
        success: false,
        content: null,
        error: error instanceof Error ? error.message : 'Unknown error',
        extractorVersion: this.version,
      };
    }
  }

  private getMimeType(extension: string): string {
    const mimeTypes: Record<string, string> = {
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg',
      png: 'image/png',
      gif: 'image/gif',
      webp: 'image/webp',
      svg: 'image/svg+xml',
      bmp: 'image/bmp',
      tiff: 'image/tiff',
      heic: 'image/heic',
    };
    return mimeTypes[extension.toLowerCase()] || 'image/jpeg';
  }

}
