import * as fs from 'fs';
import * as JSZip from 'jszip';
import type { Extractor, ExtractionResult, ExtractedContent } from './types';
import { truncateToWordLimit, withTimeout } from './extractor-utils';

/**
 * PPTX Extractor - extracts text from Microsoft PowerPoint presentations
 * Supports: .pptx
 * 
 * PPTX files are ZIP archives containing XML files. We extract text from slide XML files.
 */
export class PptxExtractor implements Extractor {
  readonly id = 'pptx-extractor';
  readonly version = '1.0.0';
  
  readonly supportedExtensions = ['pptx'];

  canExtract(extension: string): boolean {
    return this.supportedExtensions.includes(extension.toLowerCase());
  }

  async extract(filePath: string, extension: string): Promise<ExtractionResult> {
    try {
      // Check file size (skip files larger than 50MB)
      const stats = fs.statSync(filePath);
      const maxSize = 50 * 1024 * 1024; // 50MB
      if (stats.size > maxSize) {
        return {
          success: false,
          content: null,
          error: `PPTX too large (${Math.round(stats.size / 1024 / 1024)}MB), skipping`,
          extractorVersion: this.version,
        };
      }

      const dataBuffer = await withTimeout(
        fs.promises.readFile(filePath),
        60000, // 60 second timeout
        10000, // 10 second warning
        filePath
      );
      
      const zip = await withTimeout(
        JSZip.loadAsync(dataBuffer),
        60000, // 60 second timeout
        10000, // 10 second warning
        filePath
      );
      
      // Extract text from slide XML files
      const slideTexts: string[] = [];
      let slideCount = 0;
      
      // PPTX structure: ppt/slides/slide1.xml, slide2.xml, etc.
      for (const [filename, file] of Object.entries(zip.files)) {
        if (filename.startsWith('ppt/slides/slide') && filename.endsWith('.xml')) {
          slideCount++;
          try {
            const slideXml = await file.async('text');
            // Extract text content from XML (simple regex-based extraction)
            const textContent = this.extractTextFromSlideXml(slideXml);
            if (textContent.trim().length > 0) {
              slideTexts.push(`Slide ${slideCount}:\n${textContent}`);
            }
          } catch (err) {
            // Skip slides that can't be read
          }
        }
      }
      
      const rawText = slideTexts.join('\n\n---\n\n');
      
      // Truncate to 1000 words max for scalability
      const extractedText = truncateToWordLimit(rawText);
      
      // Extract keywords from text
      const keywords = this.extractKeywords(extractedText);
      
      const extractedContent: ExtractedContent = {
        contentType: 'document',
        extractedText,
        summary: null, // Summary will be generated by Summary Agent
        keywords,
        metadata: {
          size: stats.size,
          extension,
          slideCount,
          originalWordCount: rawText.split(/\s+/).filter(w => w.length > 0).length,
          truncated: rawText.length !== extractedText.length,
        },
      };

      return {
        success: true,
        content: extractedContent,
        extractorVersion: this.version,
      };
    } catch (error) {
      return {
        success: false,
        content: null,
        error: error instanceof Error ? error.message : 'Unknown error',
        extractorVersion: this.version,
      };
    }
  }

  /**
   * Extract text content from PPTX slide XML
   * PPTX uses Office Open XML format with text in <a:t> tags
   */
  private extractTextFromSlideXml(xml: string): string {
    const textMatches: string[] = [];
    
    // Extract text from <a:t> tags (text runs in PowerPoint)
    const textTagRegex = /<a:t[^>]*>(.*?)<\/a:t>/g;
    let match;
    while ((match = textTagRegex.exec(xml)) !== null) {
      const text = match[1]
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&apos;/g, "'");
      if (text.trim().length > 0) {
        textMatches.push(text.trim());
      }
    }
    
    return textMatches.join(' ');
  }

  private extractKeywords(text: string): string[] {
    const keywords: string[] = ['pptx', 'powerpoint', 'presentation'];
    
    // Simple keyword extraction
    const commonWords = ['presentation', 'slide', 'deck', 'pitch', 'proposal',
                         'report', 'summary', 'overview', 'introduction', 'conclusion'];
    
    const lowerText = text.toLowerCase();
    for (const word of commonWords) {
      if (lowerText.includes(word)) {
        keywords.push(word);
      }
    }
    
    return [...new Set(keywords)];
  }
}
