import * as fs from 'fs';
import XLSX from 'xlsx';
import type { Extractor, ExtractionResult, ExtractedContent } from './types';

/**
 * XLSX Extractor - extracts text from Microsoft Excel spreadsheets
 * Supports: .xlsx, .xls
 */
export class XlsxExtractor implements Extractor {
  readonly id = 'xlsx-extractor';
  readonly version = '1.0.0';
  
  readonly supportedExtensions = ['xlsx', 'xls'];

  canExtract(extension: string): boolean {
    return this.supportedExtensions.includes(extension.toLowerCase());
  }

  async extract(filePath: string, extension: string): Promise<ExtractionResult> {
    try {
      // Check file size (skip files larger than 50MB)
      const stats = fs.statSync(filePath);
      const maxSize = 50 * 1024 * 1024; // 50MB
      if (stats.size > maxSize) {
        return {
          success: false,
          content: null,
          error: `Excel file too large (${Math.round(stats.size / 1024 / 1024)}MB), skipping`,
          extractorVersion: this.version,
        };
      }

      const dataBuffer = await fs.promises.readFile(filePath);
      const workbook = XLSX.read(dataBuffer, { type: 'buffer' });
      
      // Extract text from all sheets
      const sheetTexts: string[] = [];
      const sheetNames: string[] = [];
      
      for (const sheetName of workbook.SheetNames) {
        const sheet = workbook.Sheets[sheetName];
        const sheetData = XLSX.utils.sheet_to_csv(sheet, { blankrows: false });
        sheetTexts.push(`Sheet: ${sheetName}\n${sheetData}`);
        sheetNames.push(sheetName);
      }
      
      const extractedText = sheetTexts.join('\n\n---\n\n');
      
      // Extract keywords from text
      const keywords = this.extractKeywords(extractedText, sheetNames);
      
      const extractedContent: ExtractedContent = {
        contentType: 'document',
        extractedText,
        summary: null, // Summary will be generated by Summary Agent
        keywords,
        metadata: {
          size: stats.size,
          extension,
          sheetCount: workbook.SheetNames.length,
          sheetNames,
        },
      };

      return {
        success: true,
        content: extractedContent,
        extractorVersion: this.version,
      };
    } catch (error) {
      return {
        success: false,
        content: null,
        error: error instanceof Error ? error.message : 'Unknown error',
        extractorVersion: this.version,
      };
    }
  }

  private extractKeywords(text: string, sheetNames: string[]): string[] {
    const keywords: string[] = ['xlsx', 'excel', 'spreadsheet'];
    
    // Add sheet names as keywords
    for (const sheetName of sheetNames) {
      keywords.push(sheetName.toLowerCase());
    }
    
    // Simple keyword extraction
    const commonWords = ['budget', 'financial', 'report', 'data', 'analysis',
                         'sales', 'revenue', 'expenses', 'invoice', 'receipt',
                         'inventory', 'tracking', 'summary'];
    
    const lowerText = text.toLowerCase();
    for (const word of commonWords) {
      if (lowerText.includes(word)) {
        keywords.push(word);
      }
    }
    
    return [...new Set(keywords)];
  }
}
